"""initial schema

Revision ID: 605cf98f5dbd
Revises: 
Create Date: 2026-08-09 23:51:10.688325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605cf98f5dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index('ix_announcement_active', ['active'], unique=False)

    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_order'), ['order'], unique=False)

    op.create_table('game_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('feature1', sa.String(length=100), nullable=True),
    sa.Column('feature2', sa.String(length=100), nullable=True),
    sa.Column('feature3', sa.String(length=100), nullable=True),
    sa.Column('feature4', sa.String(length=100), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('nest_id', sa.String(length=50), nullable=True),
    sa.Column('egg_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('backups', sa.Integer(), nullable=True),
    sa.Column('allocations', sa.Integer(), nullable=True),
    sa.Column('databases', sa.Integer(), nullable=True),
    sa.Column('sub_type', sa.String(length=30), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_plan', schema=None) as batch_op:
        batch_op.create_index('ix_game_plan_featured', ['is_featured'], unique=False)
        batch_op.create_index('ix_game_plan_game_serial', ['game', 'serial_number'], unique=False)

    op.create_table('globe_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_update_created_at'), ['created_at'], unique=False)

    op.create_table('referral_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('service_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('flag_icon', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pelican_user_id', sa.Integer(), nullable=True),
    sa.Column('pelican_password', sa.String(length=500), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pelican_user_id'), ['pelican_user_id'], unique=False)

    op.create_table('customer_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coupon_code', sa.String(length=50), nullable=True),
    sa.Column('server_name', sa.String(length=100), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.create_index('ix_customer_order_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_order_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_customer_order_user_status', ['user_id', 'status'], unique=False)

    op.create_table('server_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('pelican_server_id', sa.Integer(), nullable=True),
    sa.Column('pelican_server_identifier', sa.String(length=20), nullable=True),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('node_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['game_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('server_record', schema=None) as batch_op:
        batch_op.create_index('ix_server_record_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_server_record_identifier_user', ['pelican_server_identifier', 'user_id'], unique=False)
        batch_op.create_index('ix_server_record_panel_id', ['pelican_server_id'], unique=False)
        batch_op.create_index('ix_server_record_user_status', ['user_id', 'status'], unique=False)

    op.create_table('verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_verification_token_user_purpose', ['user_id', 'purpose'], unique=False)

    op.create_table('customer_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('software', sa.String(length=30), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['game_plan.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_ref', name='uq_payment_provider_ref')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('ix_payment_order', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_order')

    op.drop_table('payment')
    op.drop_table('customer_order_item')
    with op.batch_alter_table('verification_token', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_token_user_purpose')
        batch_op.drop_index(batch_op.f('ix_verification_token_token_hash'))

    op.drop_table('verification_token')
    with op.batch_alter_table('server_record', schema=None) as batch_op:
        batch_op.drop_index('ix_server_record_user_status')
        batch_op.drop_index('ix_server_record_panel_id')
        batch_op.drop_index('ix_server_record_identifier_user')
        batch_op.drop_index('ix_server_record_expires')

    op.drop_table('server_record')
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_order_user_status')
        batch_op.drop_index(batch_op.f('ix_customer_order_public_id'))
        batch_op.drop_index('ix_customer_order_created')

    op.drop_table('customer_order')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_pelican_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    op.drop_table('service_status')
    op.drop_table('referral_code')
    with op.batch_alter_table('maintenance_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_update_created_at'))

    op.drop_table('maintenance_update')
    op.drop_table('globe_location')
    with op.batch_alter_table('game_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_game_plan_game_serial')
        batch_op.drop_index('ix_game_plan_featured')

    op.drop_table('game_plan')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_order'))

    op.drop_table('faq')
    op.drop_table('coupon')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index('ix_announcement_active')

    op.drop_table('announcement')
    # ### end Alembic commands ###
