@extends('layouts.admin')
@section('title', 'Subdomain Manager')
@section('content-header')<h1>Subdomain Manager<small>Cloudflare DNS for customer server hostnames.</small></h1>@endsection
@section('content')
<div class="row"><div class="col-md-6"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Cloudflare</h3></div><form method="POST" action="{{ route('admin.subdomains.settings') }}"><div class="box-body">{!! csrf_field() !!}<label>Restricted API Token</label><input class="form-control" type="password" name="token" placeholder="{{ $configured ? 'Configured — enter only to replace' : 'Cloudflare DNS Edit token' }}"><p class="text-muted"><small>Grant Zone / DNS / Edit and Zone / Zone / Read only.</small></p></div><div class="box-footer"><button class="btn btn-primary">Save Token</button></div></form><form method="POST" action="{{ route('admin.subdomains.test') }}" class="box-footer">{!! csrf_field() !!}<button class="btn btn-default" {{ $configured ? '' : 'disabled' }}>Test Connection</button></form></div></div><div class="col-md-6"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Add Root Domain</h3></div><form method="POST" action="{{ route('admin.subdomains.domains.store') }}"><div class="box-body">{!! csrf_field() !!}<input class="form-control" name="domain" placeholder="fluxmc.net" required><br><input class="form-control" name="zone_id" placeholder="Cloudflare Zone ID" required><br><input class="form-control" name="max_per_server" type="number" min="1" value="1" required><br><input class="form-control" name="allowed_egg_ids" placeholder="Allowed egg IDs, comma separated (blank = all)"><br><input class="form-control" name="reserved_labels" placeholder="Reserved labels, comma separated"></div><div class="box-footer"><button class="btn btn-primary">Add Domain</button></div></form></div></div></div>
<div class="box"><div class="box-header with-border"><h3 class="box-title">Domains</h3></div><div class="table-responsive"><table class="table table-hover"><tr><th>Domain</th><th>Zone</th><th>Limit</th><th>Status</th><th></th></tr>@foreach($domains as $domain)<tr><td>{{ $domain->domain }}</td><td>{{ $domain->provider_zone_id }}</td><td>{{ $domain->max_per_server }}</td><td>{{ $domain->enabled ? 'Enabled' : 'Disabled' }}</td><td><form method="POST" action="{{ route('admin.subdomains.domains.toggle', $domain) }}">{!! csrf_field() !!}<button class="btn btn-xs btn-default">{{ $domain->enabled ? 'Disable' : 'Enable' }}</button></form></td></tr>@endforeach</table></div></div>
<div class="box"><div class="box-header with-border"><h3 class="box-title">Customer Subdomains</h3></div><div class="table-responsive"><table class="table table-hover"><tr><th>Hostname</th><th>Server</th><th>Target</th><th>Status</th><th>Last Sync</th></tr>@forelse($subdomains as $subdomain)<tr><td>{{ $subdomain->hostname }}</td><td>{{ $subdomain->server?->name }}</td><td>{{ $subdomain->target_ip }}{{ $subdomain->target_port ? ':' . $subdomain->target_port : '' }}</td><td>{{ ucfirst($subdomain->status) }}</td><td>{{ $subdomain->last_synced_at }}</td></tr>@empty<tr><td colspan="5">No customer subdomains have been created.</td></tr>@endforelse</table></div><div class="box-footer">{{ $subdomains->links() }}</div></div>
<div class="box"><div class="box-header with-border"><h3 class="box-title">Failed DNS Operations</h3></div><div class="table-responsive"><table class="table table-hover"><tr><th>Time</th><th>Operation</th><th>Hostname</th><th>Error</th></tr>@forelse($operations as $op)<tr><td>{{ $op->created_at }}</td><td>{{ $op->operation }}</td><td>{{ $op->subdomain?->hostname }}</td><td>{{ $op->message }}</td></tr>@empty<tr><td colspan="4">No failed operations.</td></tr>@endforelse</table></div></div>
@endsection
